module.exports = {
  ROLES: {
    CUSTOMER: 'CUSTOMER',
    OWNER: 'OWNER',
    STAFF: 'STAFF',
    ADMIN: 'ADMIN'
  },
  STAFF_ROLES: {
    MANAGER: 'MANAGER',
    WAITER: 'WAITER',
    KITCHEN: 'KITCHEN',
    RECEPTION: 'RECEPTION'
  },
  TABLE_STATUS: {
    AVAILABLE: 'AVAILABLE',
    RESERVED: 'RESERVED',
    OCCUPIED: 'OCCUPIED',
    PREPARING: 'PREPARING',
    CLEANING: 'CLEANING',
    OUT_OF_SERVICE: 'OUT_OF_SERVICE'
  },
  RESERVATION_STATUS: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    SEATED: 'SEATED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW'
  },
  ORDER_STATUS: {
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED',
    PREPARING: 'PREPARING',
    READY: 'READY',
    SERVED: 'SERVED',
    CANCELLED: 'CANCELLED'
  },
  WAITLIST_STATUS: {
    WAITING: 'WAITING',
    NOTIFIED: 'NOTIFIED',
    SEATED: 'SEATED',
    CANCELLED: 'CANCELLED',
    NO_SHOW: 'NO_SHOW'
  },
  CROWD_LEVEL: {
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    FULL: 'FULL'
  },
  NOTIFICATION_TYPES: {
    RESERVATION_CONFIRMED: 'RESERVATION_CONFIRMED',
    RESERVATION_CANCELLED: 'RESERVATION_CANCELLED',
    TABLE_READY: 'TABLE_READY',
    FOOD_PREPARING: 'FOOD_PREPARING',
    FOOD_READY: 'FOOD_READY',
    WAITLIST_UPDATE: 'WAITLIST_UPDATE',
    WAIT_TIME_UPDATE: 'WAIT_TIME_UPDATE',
    CROWD_ALERT: 'CROWD_ALERT'
  }
};
